### PR TITLE
Update to work with Winston 3

### PR DESCRIPTION
**Pull request by levibostian**
I have recently updated my projects to using winston v3. When I updated it, I received the error `throw new Error('Invalid transport, must be an object with a log method.')` when running `winston.add(require('winston-slacker'), options)`. 

I decided to fork the repo and get it working to the new winston 3 transports format as outlined [in this repo](https://github.com/winstonjs/winston-transport/). 

---

* All tests pass. 
* Winston now works and logs to Slack successfully after updating this logger project to the new winston 3 format. 
* Eslint does not pass. Below are the error messages I receive:

```
1:1  error  Rule 'space-after-keywords' was removed and replaced by: keyword-spacing     space-after-keywords
  1:1  error  Rule 'space-return-throw-case' was removed and replaced by: keyword-spacing  space-return-throw-case
```

To get this working, you would need to update the eslint rules used I believe. The rules are contained in another repo of yours. 

Thank you! I have used this winston logger for years and I really appreciate it. I am happy to help keep it going.

### CODE REVIEW

**Comment by levibostian** [comment]
As noted above, I expect the Travis build to fail from eslint. Unit tests, however, all pass. 

As far as eslint, I am not sure what you would like to do to fix that as it requires an update to your eslint rules in another repo.

**Comment by programbo** [comment]
Hi @levibostian, I just stumbled upon this PR by accident. This repository hasn't been looked at in years and the guy who created it works somewhere else now. We don't use Winston anymore so it's not going to be maintained here. If you want to maintain your fork I can talk to someone about letting you have `winston-slacker` on NPM. Interested?

**Comment by levibostian** [comment]
Hello, @programbo. I appreciate the offer. 

I have been using this project for years and on many projects. I would like to keep it going so myself and others can continue to use it. 

Yes, please. I would like to maintain the project on npm. 

Would it be easier to transfer this GitHub repo to me or would you like to keep it on the meerkats account, I maintain a fork, and you perhaps add a note to this project's readme saying it's no longer active? Or a note saying it works for winston <= 2.x.x For newcomers trying to get winston and slack working, they may appreciate that. 

Have an awesome day! Thank you for helping.

**Comment by programbo** [comment]
Thanks @levibostian! Once I find out who has the NPM credentials I will transfer the ownership of the repo and package 😄

**Comment by levibostian** [comment]
@programbo Have you heard any progress on this? I am still interested in maintaining the project.

**Pull request closed without merging**
